### ISSUE TITLE
Cast error

### ISSUE THREAD

**Issue by xobed** [seba76/SwaggerContextDriver#1]
Getting an error when trying to add connection with this driver:
```
LINQPad - Error
An eror has occurred:
System.InvalidCastException
Unable to cast object of type "SwaggerContext Driver. DynamicDriver' to type
"LINQPad.Extensibility. DataContext. DataContext Driver'.
```
![image](https://user-images.githubusercontent.com/8048197/34148013-fd1166e0-e49f-11e7-88d1-33b3cac172cf.png)

Using Linqpad 5.26.01
.NET Framework 4.7

**Comment by seba76** [comment]
Can you give me a link to or json used when adding connection?

**Comment by xobed** [comment]
This happens when I click on 'Add connection'. So I was not able to choose
any json file yet.

**Comment by seba76** [comment]
That is just weird. Can you check content of following folder:
c:\Users\<YourUser>\AppData\Local\LINQPad\Drivers\DataContext\4.6\SwaggerContextDriver (no-strong-name)\
It should have following files:
Connection.png
DotLiquid.dll
DotLiquid.xml
FailedConnection.png
header.xml
Newtonsoft.Json.dll
Newtonsoft.Json.xml
NJsonSchema.dll
NJsonSchema.xml
NJsonSchema.CodeGeneration.dll
NJsonSchema.CodeGeneration.xml
NJsonSchema.CodeGeneration.CSharp.dll
NJsonSchema.CodeGeneration.CSharp.xml
NSwag.CodeGeneration.dll
NSwag.CodeGeneration.xml
NSwag.CodeGeneration.CSharp.dll
NSwag.CodeGeneration.CSharp.xml
NSwag.Core.dll
NSwag.Core.xml
SwaggerContextDriver.dll
SwaggerContextDriver.pdb
Only thing that comes to mind is that some of the files are missing. DinamicDriver class is derived from DynamicDataContextDriver class from LinqPad exe which in turn is derived from DataContextDriver so cast must be valid.

**Comment by xobed** [comment]
I have re-downloaded the driver and now it seems to work OK.

Closing.
