### ISSUE TITLE
Unable to provide different credentials when getting 401

### ISSUE THREAD

**Issue by kachalkov** [seba76/SwaggerContextDriver#2]
Dialog options for alternative windows credentials are always disabled?

**Comment by kachalkov** [comment]
great job on the swagger driver!

**Comment by seba76** [comment]
Yes, it is disabled because I never got time write actual code that will perform authentication. I have plans to do it but can't give you specific timeline. 

Pull requests are welcome.

**Comment by kachalkov** [comment]
Right, at least having UseDefaultCredentials for http client would do for now

**Comment by kachalkov** [comment]
I've had a look, can't see how to add HttpClient to the generated code...

**Comment by mybura** [comment]
Added the code for the credentials. Seems to work okay for Current User. 

There is a 401 when using Basic auth while invoking your User Query. Suspecting a double hop issue at this stage.

**Comment by kachalkov** [comment]
thank you very much guys works like a charm!

now, how hard would be to have Azure Login? :)

should I just populate OAuth Token manually into Http Client?

**Comment by seba76** [comment]
Populating OAuth token manually into http client should work. For this you should use inject http client option (if I remember correctly) and add token to it so it would work. But keep in mind that token has to be refreshed from time to time, which depends on server settings.
